name: Playwright Tests
on:
  deployment_status:

jobs:
  test:
   # We deploy multiple sites from main branch, which makes the setup quite tricky.
    # So we're only testing on Preview Env deployments in Pull Requests, which should be enough.
    if: >-
      !contains(fromJSON('["Production – theme-nextjs-lena-cookbook", "Production – theme-nextjs-lena-photography", "Production – theme-nextjs-lena-preview", "Production – theme-nextjs-lena-the-good-newsroom"]'), github.event.deployment.environment)
    uses: prezly/theme-kit-js/.github/workflows/playwright.shared.yml@main
    with:
      site-name: 'Preview Env'
